# Обучить сеть Хопфилда распознавать 4 изображения


In [27]:
import numpy as np

In [28]:
def Sign(a):
  for i in range(len(a)):
    if a[i] > 0:
      a[i] = 1
    else:
      a[i] = -1
  return a


In [29]:
# Проверяем изображение
def check (b):
  t1 = w @ b
  T1 = Sign(t1)
  T2 = np.zeros(len(T1))
  
  while T2.all() != T1.all():
    t2 = w @ Sign(t1)
    T2 = Sign(t2)
    if T2.all() == T1.all():
      break
    t1 = w @ T2
    T1 = Sign(t1)

  count = 0
  for i in range(len(T2)): 
   if T2[i] == x_1[i]:
     count += 1
     if count == 36:
       print('1-ая эталонная картинка')

  count = 0
  for i in range(len(T2)): 
   if T2[i] == x_2[i]:
     count += 1
     if count == 36:
       print('2-ая эталонная картинка')

  count = 0
  for i in range(len(T2)): 
   if T2[i] == x_3[i]:
     count += 1
     if count == 36:
       print('3-ья эталонная картинка')

  count = 0
  for i in range(len(T2)): 
   if T2[i] == x_4[i]:
     count += 1
     if count == 36:
       print('4-ая эталонная картинка')
    
  return T2

In [30]:
# Эталонные
x_1 = np.array([-1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1])
x_2 = np.array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, -1, -1, -1, 1, 1, 1, -1, -1, -1, 1, 1, 1, -1, -1, -1])
x_3 = np.array([-1, -1, -1, 1, 1, 1, -1, -1, -1, 1, 1, 1, -1, -1, -1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])
x_4 = np.array([-1, -1, -1, -1, -1, -1, -1, -1, 1, 1, -1, -1, -1, 1, -1, -1, 1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [31]:
# Искаженные картинки
y_1 = np.array([-1, -1, 1, 1, 1, 1, -1, -1, -1, -1, 1, 1, 1, -1, -1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, 1, -1, 1, 1, -1, -1, -1, 1])
y_2 = np.array([-1, -1, -1, -1, -1, 1, -1, -1, -1, 1, 1, -1, -1, -1, -1, 1, -1, 1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])
y_3 = np.array([-1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1])
y_4 = np.array([-1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1])
y_5 = np.array([-1, -1, -1, -1, 1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 1, -1, -1, -1, 1, -1, 1, 1, -1, -1, 1, -1, 1, -1, -1, 1])
y_6 = np.array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, -1, -1, -1, 1, 1, 1, -1, -1, -1, 1, 1, 1, -1, -1, -1])


In [32]:
# Получим матрицу весовых коэффициентов
w = np.zeros([len(x_1), len(x_1)])
for i in range(len(x_1)):
  for j in range(i, len(x_1)):
    if i == j:
      w[i,j] = 0
    else:
      w[i,j] = x_1[i]*x_1[j] + x_2[i]*x_2[j] + x_3[i]*x_3[j] + x_4[i]*x_4[j]
      w[j,i] = w[i,j]
print('Матрица коэффициентов:')
w

Матрица коэффициентов:


array([[0., 4., 4., ..., 4., 4., 4.],
       [4., 0., 4., ..., 4., 4., 4.],
       [4., 4., 0., ..., 4., 4., 4.],
       ...,
       [4., 4., 4., ..., 0., 4., 4.],
       [4., 4., 4., ..., 4., 0., 4.],
       [4., 4., 4., ..., 4., 4., 0.]])

In [33]:
check(y_1)

array([-1., -1., -1., -1., -1.,  1., -1., -1., -1., -1.,  1., -1., -1.,
       -1., -1.,  1.,  1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.])

In [34]:
check(y_2)

array([-1., -1., -1., -1., -1.,  1., -1., -1., -1.,  1.,  1., -1., -1.,
       -1., -1.,  1.,  1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.])

In [35]:
check(y_3)

1-ая эталонная картинка


array([-1., -1., -1., -1., -1.,  1., -1., -1., -1., -1.,  1., -1., -1.,
       -1., -1.,  1., -1., -1., -1., -1.,  1., -1., -1., -1., -1.,  1.,
       -1., -1., -1., -1.,  1., -1., -1., -1., -1., -1.])

In [36]:
check(y_4)

1-ая эталонная картинка


array([-1., -1., -1., -1., -1.,  1., -1., -1., -1., -1.,  1., -1., -1.,
       -1., -1.,  1., -1., -1., -1., -1.,  1., -1., -1., -1., -1.,  1.,
       -1., -1., -1., -1.,  1., -1., -1., -1., -1., -1.])

In [37]:
check(y_5)

2-ая эталонная картинка


array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1.,  1.,  1.,  1., -1., -1., -1.,  1.,  1.,
        1., -1., -1., -1.,  1.,  1.,  1., -1., -1., -1.])

In [38]:
check(y_6)

2-ая эталонная картинка


array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1.,  1.,  1.,  1., -1., -1., -1.,  1.,  1.,
        1., -1., -1., -1.,  1.,  1.,  1., -1., -1., -1.])

# Построить двунаправленную ассоциативную память

In [39]:
import numpy as np

In [40]:
one = np.array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1])
two = np.array([-1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, 1, 1, 1, 1, 1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1])
three = np.array([-1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1])

In [41]:
e_1 = np.array([-1, -1, 1])
e_2 = np.array([-1, 1, -1])
e_3 = np.array([-1, 1, 1])

In [42]:
w = np.zeros([len(one), len(e_1)])
for i in range(len(one)):
  for j in range(len(e_1)):
    w[i][j] = one[i]*e_1[j] + two[i]*e_2[j] + three[i]*e_3[j]
print('Матрица коэффициентов:')
w

Матрица коэффициентов:


array([[ 3., -1., -1.],
       [ 3., -1., -1.],
       [ 3., -1., -1.],
       [ 3., -1., -1.],
       [ 3., -1., -1.],
       [ 3., -1., -1.],
       [ 3., -1., -1.],
       [ 3., -1., -1.],
       [-1.,  3., -1.],
       [-1.,  3., -1.],
       [-3.,  1.,  1.],
       [-1.,  3., -1.],
       [-1.,  3., -1.],
       [ 3., -1., -1.],
       [ 3., -1., -1.],
       [ 3., -1., -1.],
       [ 1., -3.,  1.],
       [ 1., -3.,  1.],
       [ 3., -1., -1.],
       [-1.,  3., -1.],
       [ 3., -1., -1.],
       [ 3., -1., -1.],
       [ 3., -1., -1.],
       [ 3., -1., -1.],
       [ 1., -3.,  1.],
       [ 3., -1., -1.],
       [-1.,  3., -1.],
       [ 3., -1., -1.],
       [ 3., -1., -1.],
       [ 1.,  1., -3.],
       [ 1.,  1., -3.],
       [-3.,  1.,  1.],
       [-1.,  3., -1.],
       [-1.,  3., -1.],
       [ 3., -1., -1.],
       [ 3., -1., -1.],
       [ 1.,  1., -3.],
       [ 3., -1., -1.],
       [ 1., -3.,  1.],
       [ 3., -1., -1.],
       [ 1.,  1.,  1.],
       [ 3., -1.

In [43]:
def Sign(a):
  for i in range(len(a)):
    if a[i] > 0:
      a[i] = 1
    else:
      a[i] = -1
  return a


In [44]:
Sign(two @ w)

array([-1.,  1.,  1.])

In [45]:
Sign(one @ w)

array([-1., -1.,  1.])

# Построить двунаправленную ассоциативную память, связывающую изображение из файла с его сжатым вариантом

In [46]:
import numpy as np
from PIL import Image


In [48]:
arrow = Image.open('arrow.bmp')
pressed_arrow = Image.open('pressed_arrow.bmp')

In [49]:
gray = arrow.convert('L')
 
a1 = np.array(gray.getdata())
for i in range(len(a1)):
  if a1[i] > 0:
    a1[i] = 1
  else:
    a1[i] = -1
a1

array([-1, -1, -1, ..., -1, -1, -1])

In [50]:
gray = pressed_arrow.convert('L')

a2 = np.array(gray.getdata())
for i in range(len(a2)):
  if a2[i] > 0:
    a2[i] = 1
  else:
    a2[i] = -1
a2

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1,  1,  1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        1,  1,  1, -1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1,
        1, -1, -1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1,  1,  1,  1, -1,
       -1, -1,  1,  1,  1, -1, -1, -1, -1, -1, -1,  1,  1,  1, -1, -1, -1,
       -1,  1,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1, -1, -1, -1, -1, -1,
        1,  1,  1, -1, -1, -1, -1,  1,  1,  1, -1, -1, -1, -1, -1, -1,  1,
        1,  1, -1, -1, -1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1,  1,  1

In [51]:
w = np.zeros([len(a1), len(a2)])
for i in range(len(a1)):
  for j in range(len(a2)):
    w[i][j] = a1[i]*a2[j]
print('Матрица коэффициентов:')
w

Матрица коэффициентов:


array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [52]:
def Sign(a):
  for i in range(len(a)):
    if a[i] > 0:
      a[i] = 1
    else:
      a[i] = -1
  return a

In [53]:
s = Sign(a1 @ w)
print(s)
count = 0
for i in range(len(a2)): 
  if s[i] == a2[i]:
    count += 1
    if count == len(a2):
      print('Полученный массив совпадает со сжатой картинкой')

[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. -1. -1. -1. -1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1. -1. -1. -1. -1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.
  1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1.  1.  1.
  1.  1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1.  1. -1.  1.  1.  1.
 -1. -1. -1. -1. -1. -1. -1. -1.  1.  1.  1. -1. -1.  1.  1.  1. -1. -1.
 -1. -1. -1. -1. -1.  1.  1.  1. -1. -1. -1.  1.  1.  1. -1. -1. -1. -1.
 -1. -1.  1.  1.  1. -1. -1. -1. -1.  1.  1.  1. -1. -1. -1. -1. -1.  1.
  1.  1. -1. -1. -1. -1. -1.  1.  1.  1. -1. -1. -1. -1.  1.  1.  1. -1.
 -1. -1. -1. -1. -1.  1.  1.  1. -1. -1. -1.  1.  1.  1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1.  1.  1. -1. -1. -1. -1. -1