In [ ]:
import numpy as np

In [ ]:
#Эталонные образы для индексов 
x_0 = np.array([1, 1, 1, 1, -1, 1, 1, -1, 1, 1, -1, 1, 1, 1, 1])
x_1 = np.array([-1, -1, 1, -1, 1, 1, 1, -1, 1, -1, -1, 1, -1, -1, 1])
x_2 = np.array([1, 1, 1, -1, -1, 1, -1, -1, 1, -1, 1, -1, 1, 1, 1])
x_3 = np.array([1, 1, 1, -1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1, -1])
x_4 = np.array([1, -1, -1, 1, -1, 1, 1, 1, 1, -1, -1, 1, -1, -1, 1])
x_5 = np.array([1, 1, 1, 1, -1, -1, 1, 1, 1, -1, -1, 1, 1, 1, 1])
x_6 = np.array([-1, -1, 1, -1, 1, -1, 1, 1, 1, 1, -1, 1, 1, 1, 1])
x_7 = np.array([1, 1, 1, -1, 1, -1, 1, -1, -1, 1, -1, -1, 1, -1, -1])
x_8 = np.array([1, 1, 1, 1,  -1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1])
x_9 = np.array([1, 1, 1, 1, -1, 1, 1, 1, 1, -1, 1, -1, 1, -1, -1])
np.shape(x_0), np.shape(x_1), np.shape(x_2), np.shape(x_3), np.shape(x_4), np.shape(x_5), np.shape(x_6), np.shape(x_7), np.shape(x_8), np.shape(x_9)

((15,), (15,), (15,), (15,), (15,), (15,), (15,), (15,), (15,), (15,))

In [ ]:
#Формируем матрицу весов первого слоя
W = np.vstack((x_0, x_1, x_2, x_3, x_4, x_5, x_6, x_7, x_8, x_9)) #вертикальное объединение массивов
W = 0.5*W
W

array([[ 0.5,  0.5,  0.5,  0.5, -0.5,  0.5,  0.5, -0.5,  0.5,  0.5, -0.5,
         0.5,  0.5,  0.5,  0.5],
       [-0.5, -0.5,  0.5, -0.5,  0.5,  0.5,  0.5, -0.5,  0.5, -0.5, -0.5,
         0.5, -0.5, -0.5,  0.5],
       [ 0.5,  0.5,  0.5, -0.5, -0.5,  0.5, -0.5, -0.5,  0.5, -0.5,  0.5,
        -0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5, -0.5,  0.5, -0.5,  0.5,  0.5,  0.5, -0.5,  0.5,
        -0.5,  0.5, -0.5, -0.5],
       [ 0.5, -0.5, -0.5,  0.5, -0.5,  0.5,  0.5,  0.5,  0.5, -0.5, -0.5,
         0.5, -0.5, -0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5, -0.5, -0.5,  0.5,  0.5,  0.5, -0.5, -0.5,
         0.5,  0.5,  0.5,  0.5],
       [-0.5, -0.5,  0.5, -0.5,  0.5, -0.5,  0.5,  0.5,  0.5,  0.5, -0.5,
         0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5, -0.5,  0.5, -0.5,  0.5, -0.5, -0.5,  0.5, -0.5,
        -0.5,  0.5, -0.5, -0.5],
       [ 0.5,  0.5,  0.5,  0.5, -0.5,  0.5,  0.5,  0.5,  0.5,  0.5, -0.5,
         0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5, -0.5,

In [ ]:
#Порог активационной функции
T = 15/2
#Ограничение эпсилон
eps = 0.1
#Матрица V
V = np.eye(10) 
V[V == 0] = -eps
V

array([[ 1. , -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1,  1. , -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1,  1. , -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1,  1. , -0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1,  1. , -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1,  1. , -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1,  1. , -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1,  1. , -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1,  1. , -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1,  1. ]])

In [ ]:
#Тестовые образы
x_test = np.array([-1, -1, 1, -1, 1, 1, 1, -1, 1, -1, -1, 1, -1, -1, 1])
Y1 = W @ x_test + T
Y1[Y1 > T] = T
Y1[Y1 < 0] = 0
print('Y1:', Y1)

stab = 100
while stab > 0.1:
  Y2 = V @ Y1
  Y2[Y2 >= T] = T
  Y2[Y2 < 0] = 0
  print('Ynext:', Y2)
  stab = sum((Y2 - Y1)**2)
  Y1 = Y2
for i in  range (len(Y2)):
  if Y2[i] > 0:
    print (i)
stab, Y2

Y1: [7.5 7.5 7.  7.  7.5 7.  7.5 7.  7.  6. ]
Ynext: [1.15 1.15 0.6  0.6  1.15 0.6  1.15 0.6  0.6  0.  ]
Ynext: [0.505 0.505 0.    0.    0.505 0.    0.505 0.    0.    0.   ]
Ynext: [0.3535 0.3535 0.     0.     0.3535 0.     0.3535 0.     0.     0.    ]
0
1
4
6


(0.09180899999999999,
 array([0.3535, 0.3535, 0.    , 0.    , 0.3535, 0.    , 0.3535, 0.    ,
        0.    , 0.    ]))